[package]
name = "localproxy"
version = "0.1.0"
edition = "2021"

[dependencies]
quinn = { version = "0.11.6", default-features = false, features = [
    "runtime-tokio",
    "rustls",
]}
rcgen = { version = "0.13.2", features = ["x509-parser", "crypto"] }
rustls = { version = "0.23.20", default-features = true }
tokio = { version = "1.42.0", features = ["full"] }
tokio-socks = "0.5.2"
time = "0.3.37"

[[bin]]
name = "localproxy"
path = "src/bin/local_proxy.rs"

[[bin]]
name = "remoteproxy"
path = "src/bin/remote_proxy.rs"

[[bin]]
name = "certgenerate"
path = "src/bin/cert_generate.rs"
